### ISSUE TITLE
티스토리에 덛글이 작성이 안되서 여기에 남겨요 죄송 하옵니다.

### ISSUE THREAD

**Issue by oklokl** [Sangmoo/moober-eats-backend#1]
https://sangmoo.tistory.com/301

https://kin.naver.com/qna/detail.naver?d1id=1&dirId=104&docId=432645093
제가 하고 있는 고민인대요? 드롭에 써먹고 싶은대 잘 안되네요 ㅠㅠ..
ip를 등록 하고 싶은대. 드롭해서 관리자 권한으로 실행 하고 싶어서요.
즉 문서를 드롭 하면 관리자 권한으로 실행 되면서 입력 까지 되게 하고 싶어요 불가능 할까요?

먼가 만들고 싶은대 쉽지 않네요 ㅠㅠ.. 배치 파일 만드는 중인대 너무 어렵네요. 

,

,

,

,

#######################################
다른 이야기

그리고요 티스토리 문제 아래 빨간 영역은 제가 지운게 아니라. 엣지로 해도 안보이고요. 파이어 폭스 크롬으로 해도 안보이더라고요 버그 같아요.

![444](https://user-images.githubusercontent.com/1571600/201563530-23d6b1ab-0312-425d-be04-73f83e46626a.png)
그림 처럼 스팸 차단 그림문자를 골라야 하는대 고를수가 없네요 ㅎㅎ
혹시나? 해서 고객센터에 이야기 해놨어요. ㅎㅎ.. 연락이 안되시면..

**Comment by Sangmoo** [comment]
안녕하세요, 
https://kin.naver.com/qna/detail.naver?d1id=1&dirId=104&docId=432645093
해당 지식인 링크에 올려주신 다른분의 답변대로 진행을 해봤는데,
 
@echo off
chcp 65001 > nul
BCDEDIT > nul
if "%ERRORLEVEL%" EQU "1" Powershell.exe -Command "& {Start-Process """%0""" -Verb RunAs}" & exit
title 관리자 권한이 시작 되었습니다.
for /f "delims=" %%a in ('type "C:\Users\jsj94\Desktop\test.txt"') do (
netsh advfirewall firewall add rule name="AAA" dir=in action=block protocol=ANY remoteip="%%a"
)
pause
 
bat파일에서 for문 부분 " for /f "delims=" %%a in ('type "C:\Users\jsj94\Desktop\test.txt"') "
이부분에서 test.txt파일의 경로만 제대로 인식시켜주면 정상 처리되는걸로 나옵니다.
 
 
 
저의 경우 D드라이브 test.txt 파일 생성 후 임의 ip 4개를 넣고 테스트 해봤는데
Ok로 떨어집니다.
 
티스토리 덧글문제같은경우는 고객센터 답변 받으시고나서 피드백 주시면 처리해보겠습니다!
 
 
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2022-11-14 (월) 11:39:06 (GMT+09:00)
Subject: [Sangmoo/moober-eats-backend] 티스토리에 덛글이 작성이 안되서 여기에 남겨요 죄송 하옵니다. (Issue #1)
 
https://sangmoo.tistory.com/301
https://kin.naver.com/qna/detail.naver?d1id=1&dirId=104&docId=432645093
제가 하고 있는 고민인대요? 드롭에 써먹고 싶은대 잘 안되네요 ㅠㅠ..
ip를 등록 하고 싶은대. 드롭해서 관리자 권한으로 실행 하고 싶어서요.
즉 문서를 드롭 하면 관리자 권한으로 실행 되면서 입력 까지 되게 하고 싶어요 불가능 할까요?
먼가 만들고 싶은대 쉽지 않네요 ㅠㅠ.. 배치 파일 만드는 중인대 너무 어렵네요.
그리고요 티스토리 문제

그림 처럼 스팸 차단 그림문자를 골라야 하는대 고를수가 없네요 ㅎㅎ
혹시나? 해서 고객센터에 이야기 해놨어요. ㅎㅎ.. 연락이 안되시면..

**Comment by oklokl** [comment]
바쁘신대 너무 ㄳ 드려요 ㅎㅎ.. 올리고 있어요 신나서 ㅋㅋ 잘 되네요. 전승환님도 도와 주셨어요 지식인.
전 똥손 컴맹이라 ㅠㅠ.. 아무리 해도 안되더라고요 ㅎㅎ 너무 ㄳ 드립니다 화팅

**Comment by Sangmoo** [comment]
해결되셨다니 다행이네요 고생하세요!
